# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None
base_dir = os.path.abspath('.')

a = Analysis(
    ['main.py'],
    pathex=[base_dir],
    binaries=[],
    datas=[
        ('frontend/dist', 'frontend/dist'),
        ('models', 'models'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'starlette.responses',
        'starlette.staticfiles',
        'starlette.middleware.cors',
        'multipart',
        'torch',
        'torch.nn',
        'torch.nn.functional',
        'torch.optim',
        'numpy',
        'scipy',
        'scipy.io',
        'scipy.io.matlab',
        'h5py',
        'sklearn',
        'sklearn.metrics',
        'PIL',
        'PIL.Image',
        'pywt',
        'tqdm',
        'plotly',
        'pandas',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'IPython',
        'jupyter',
        'notebook',
        'PySide6',
        'PySide2',
        'PyQt4',
        'PyQt6',
        'sphinx',
        'numba',
        'llvmlite',
        'dask',
        'pytest',
        'zmq',
        'pyarrow',
        'botocore',
        'boto3',
        'tensorflow',
        'keras',
        'tensorboard',
        'grpc',
        'bokeh',
        'altair',
        'streamlit',
        'gradio',
        'torchvision',
        'torchaudio',
        'openpyxl',
        'lxml',
        'tables',
        'sqlalchemy',
        'qtpy',
        'PyQt5',
        'pydub',
        'nbformat',
        'ruamel',
        'argon2',
        'docutils',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PINN故障诊断系统',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='PINN故障诊断系统',
)
